name: Build Debug APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Download and Setup Gradle 8.4
        run: |
          wget https://services.gradle.org/distributions/gradle-8.4-bin.zip
          unzip -q gradle-8.4-bin.zip
          echo "$PWD/gradle-8.4/bin" >> $GITHUB_PATH

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.4

      - name: Build Debug APK with Gradle Wrapper
        run: ./gradlew assembleDebug

      - name: Rename APK File
        run: mv app/build/outputs/apk/debug/*.apk app/build/outputs/apk/debug/mlotconnet.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlotconnet-apk
          path: app/build/outputs/apk/debug/mlotconnet.apk
          
